name: ${CLUSTER_NAME:-zabbix-composed}

services:
  database:   # Postgresql Database for backend.
    image: postgres:15-alpine
    container_name: ${CLUSTER_NAME:-zabbix-composed}-database
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=zabbix
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:     # Zabbix backend
    image: zabbix/zabbix-server-pgsql:${ZBX_VERSION:-latest}
    container_name: ${CLUSTER_NAME:-zabbix-composed}-backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "10051" ]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      - DB_SERVER_HOST=${CLUSTER_NAME:-zabbix-composed}-database
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}

  snmptraps:  # SNMP Traps
    image: zabbix/zabbix-snmptraps:${ZBX_VERSION:-latest}
    container_name: ${CLUSTER_NAME:-zabbix-composed}-snmp-traps
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps:rw
      - mibs:/usr/share/snmp/mibs:ro
    ports:
      - "162:1162/udp"

  frontend:
    image: zabbix/zabbix-web-nginx-pgsql:${ZBX_VERSION:-latest}
    container_name: ${CLUSTER_NAME:-zabbix-composed}-frontend
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    environment:
      - ZBX_SERVER_HOST=${CLUSTER_NAME:-zabbix-composed}-backend
      - DB_SERVER_HOST=${CLUSTER_NAME:-zabbix-composed}-database
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=zabbix
    ports:
      - "${SECURE_FRONT_END_PORT}:8443"
      - "${FRONT_END_PORT}:8080"
    volumes:
      - nginx:/etc/ssl/nginx:ro

  agent2:
    image: zabbix/zabbix-agent2:${ZBX_VERSION:-latest}
    container_name: ${CLUSTER_NAME:-zabbix-composed}-linux-agent-v2
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    environment:
      - ZBX_HOSTNAME=127.0.0.1
      - ZBX_SERVER_HOST=${CLUSTER_NAME:-zabbix-composed}-backend

volumes:
  db_data:    # This volume persists database data
  snmptraps:  # For SNMP traps
  mibs:       # For SNMP traps
  nginx:      # Frontend`s nginx files